sonar.projectKey=alexlealch_python-project-174
sonar.projectName=Gendiff
sonar.projectVersion=1.0
sonar.sources=gendiff
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
